# Use cpp to enable both R & Python
language: r
r: release

os: linux
dist: xenial

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/
    - /bugfix\/.*/

env:
  global:
  # Don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

# Use cache for packages
cache:
  apt: true
  packages: true
  directories:
    - $HOME/miniconda3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - git
      - gcc-7
      - g++-7
      - gfortran-7
      - libcurl4-openssl-dev
      - libxml2-dev
      - libgit2-dev
      - libharfbuzz-dev
      - libfribidi-dev

jobs:
  include:
  - name: 'Test R codes'
    env: TARGET='R'
  - name: 'Test Python codes (Python 3.6)'
    env: TARGET='Python' && PYTHON_VERSION=3.6
  - name: 'Test Python codes (Python 3.7)'
    env: TARGET='Python' && PYTHON_VERSION=3.7
  - name: 'Test Python codes (Python 3.8)'
    env: TARGET='Python' && PYTHON_VERSION=3.8

before_install:
  - export ROOTPATH=`pwd`
  - export MAKEFLAGS='-j 2'
  - export CC=gcc-7
  - export CXX=g++-7
  - if [ "$TARGET" = "R" ]; then cd $ROOTPATH/R; fi
  - if [ "$TARGET" = "Python" ]; then cd $ROOTPATH/Python; fi

install:
  - source $ROOTPATH/travis/setup.sh

script:
  - source $ROOTPATH/travis/script.sh

after_failure:
  - source $ROOTPATH/travis/after-failure.sh

after_success:
  - source $ROOTPATH/travis/after-success.sh
