ignore:
  - "R/docs/**/*"
  - "R/inst/**/*"
  - "R/man/**/*"
  - "R/src/**/*"
  - "R/tools/**/*"
  - "Python/docs/**/*"
  - "Python/hbayesdm/models/**/*"
  - "Python/hbayesdm/preprocess_funcs.py"
  - "JSON/ValidateAll.sh"

comment: false
